#!/bin/sh
#
# $FreeBSD: release/9.1.0/etc/rc.d/dmesg 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: dmesg
# REQUIRE: mountcritremote cleanvar
# BEFORE:  DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="dmesg"
rcvar="dmesg_enable"
dmesg_file="/var/run/dmesg.boot"
start_cmd="do_dmesg"
stop_cmd=":"

do_dmesg()
{
	rm -f ${dmesg_file}
	( umask 022 ; /sbin/dmesg $rc_flags > ${dmesg_file} )
}

load_rc_config $name
run_rc_command "$1"
