#!/bin/sh
#
# $FreeBSD: release/9.1.0/etc/rc.d/ftpd 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: ftpd
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

. /etc/rc.subr

name="ftpd"
rcvar="ftpd_enable"
command="/usr/libexec/${name}"
pidfile="/var/run/${name}.pid"
start_precmd=ftpd_prestart

ftpd_prestart()
{
	rc_flags="-D ${rc_flags}"
	return 0
}

load_rc_config $name
run_rc_command "$1"
