#!/bin/sh
#
# $FreeBSD: release/9.1.0/etc/rc.d/mrouted 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: mrouted
# REQUIRE: netif routing cleanvar
# KEYWORD: nojail

. /etc/rc.subr

name="mrouted"
rcvar="mrouted_enable"
command="/usr/local/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
