#!/bin/sh
#
# $FreeBSD: release/9.1.0/etc/rc.d/newsyslog 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: newsyslog
# REQUIRE: cleanvar mountcritremote

. /etc/rc.subr

name="newsyslog"
rcvar="newsyslog_enable"
required_files="/etc/newsyslog.conf"
command="/usr/sbin/${name}"
start_cmd="newsyslog_start"
stop_cmd=":"

newsyslog_start()
{
	check_startmsgs && echo -n 'Creating and/or trimming log files'
	${command} ${rc_flags}
	check_startmsgs && echo '.'
}

load_rc_config $name
run_rc_command "$1"
